---
# for a list of available hooks: https://pre-commit.com/hooks.html
default_language_version:
  python: python3.11
fail_fast: true
exclude: |
  (?x)^(
      .*/migrations/.*|
      docs/
  )$
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.7.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args:
          - --check
  - repo: https://github.com/JulienLajugie/add-missing-init
    rev: v0.0.16
    hooks:
      - id: add-missing-init
        args:
          - --folders-to-ignore
          - .
          - src
          - tests
          - docs/source
          - --
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        args:
          - --safe
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==22.6.0
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master, --branch, develop]
      - id: check-added-large-files
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: >-
          tests/.*/resources/.*
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--django]
        exclude: |
          (?x)^(
            tests/.*/resources/.*
            |tests/.*/resource/.*
            |tests/fixtures/.*
            |.*/unit_test_utils.py
            |.*/fake_wes_client.py
            |.*/assert_utils.py
            |.*/mock_response.py
          )$
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            .*\.tsv
            |tests/.*/resources/.*
          )$
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '80']
  - repo: https://github.com/wemake-services/dotenv-linter
    rev: 0.4.0
    hooks:
      - id: dotenv-linter
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        language_version: python3.10
        exclude: ^docs/|^build/|^tests/|^src/trip/runner/plugins_v2/.*/suites/.*
